daemon:
  name: "lris2csu"  # Name under which it subscribes and publishes
  mktl:
    cmd_port: 5555
    pub_port: 5557
    registry: "tcp://127.0.0.1:7000"

#1.563 mm/tooth
#370:1 gear ratio
# 38 teeth on motor

# 59.69 mm/rev
#gear head 29198/79*1024 count/rev
# = 0.1577159475 um/count
#67.072 @ 1000000
#28.178 @ 86
# = 0.038897 um/count
#looks to be about 1/4th adopt 0.03942899

#right inboard side is 9.33 proud
#right side staggers my 8.11
#left inboard side is 19.65 proud
#left side staggers by 8.2
#sides should stagger by same around so tage average of 8.16 mm
#Use furthest out (right inboard) as "true" 0 mm, all offsets are relative to this then

hardware: !CSUHardwareConfig
  ethercat_device: "eno1"  # Device for connecting to the EtherCAT bus
  left_brake: 'lris2.csu_break.left'
  right_brake: 'lris2.csu_break.right'
  bar_pairs:
    - !BarPairConfig
      id: 11
      left: !BarConfig
        bus_id: 23
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: False
        offset_mm: 18.48
        use_ssi_encoder: False
      right: !BarConfig
        bus_id: 11
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: True
        offset_mm: 0
        use_ssi_encoder: False
    - !BarPairConfig
      id: 10
      left: !BarConfig
        bus_id: 22
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: False
        offset_mm: 10.32
        use_ssi_encoder: False
      right: !BarConfig
        bus_id: 10
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: True
        offset_mm: 8.16
        use_ssi_encoder: False
    - !BarPairConfig
      id: 9
      left: !BarConfig
        bus_id: 21
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: False
        offset_mm: 18.48
        use_ssi_encoder: False
      right: !BarConfig
        bus_id: 9
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: True
        offset_mm: 0
        use_ssi_encoder: False
    - !BarPairConfig
      id: 8
      left: !BarConfig
        bus_id: 20
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: False
        offset_mm: 10.32
        use_ssi_encoder: False
      right: !BarConfig
        bus_id: 8
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: True
        offset_mm: 8.16
        use_ssi_encoder: False
    - !BarPairConfig
      id: 7
      left: !BarConfig
        bus_id: 19
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: False
        offset_mm: 18.48
        use_ssi_encoder: False
      right: !BarConfig
        bus_id: 7
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: True
        offset_mm: 0
        use_ssi_encoder: False
    - !BarPairConfig
      id: 6
      left: !BarConfig
        bus_id: 18
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: False
        offset_mm: 10.32
        use_ssi_encoder: False
      right: !BarConfig
        bus_id: 6
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: True
        offset_mm: 8.16
        use_ssi_encoder: False
    - !BarPairConfig
      id: 5
      left: !BarConfig
        bus_id: 0
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: True
        offset_mm: 18.48
        use_ssi_encoder: True
      right: !BarConfig
        bus_id: 12
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: False
        offset_mm: 0
        use_ssi_encoder: True
    - !BarPairConfig
      id: 4
      left: !BarConfig
        bus_id: 1
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: True
        offset_mm: 10.32
        use_ssi_encoder: True
      right: !BarConfig
        bus_id: 13
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: False
        offset_mm: 8.16
        use_ssi_encoder: True
    - !BarPairConfig
      id: 3
      left: !BarConfig
        bus_id: 2
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: True
        offset_mm: 18.48
        use_ssi_encoder: True
      right: !BarConfig
        bus_id: 14
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: False
        offset_mm: 0
        use_ssi_encoder: True
    - !BarPairConfig
      id: 2
      left: !BarConfig
        bus_id: 3
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: True
        offset_mm: 10.32
        use_ssi_encoder: False
      right: !BarConfig
        bus_id: 15
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: False
        offset_mm: 8.16
        use_ssi_encoder: False
    - !BarPairConfig
      id: 1
      left: !BarConfig
        bus_id: 4
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: True
        offset_mm: 18.48
        use_ssi_encoder: False
      right: !BarConfig
        bus_id: 16
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: False
        offset_mm: 0
        use_ssi_encoder: False
    - !BarPairConfig
      id: 0
      left: !BarConfig
        bus_id: 5
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: True
        offset_mm: 10.32
        use_ssi_encoder: False
      right: !BarConfig
        bus_id: 17
        torque_limit: 2.0
        speed: 6000
        um_per_count: 0.03942899
        reversed: False
        offset_mm: 8.16
        use_ssi_encoder: False