loggers:
  csuserver:
    cooethercat: DEBUG
    pysoem: DEBUG
    lris2csu: DEBUG
    lris2csu.util: INFO
    mktl: DEBUG
    "":
      handlers: [ default ]
      level: WARNING
      propagate: False
    __main__: DEBUG
  csuclient:
    cooethercat: DEBUG
    pysoem: DEBUG
    lris2csu: DEBUG
    lris2csu.util: INFO
    mktl: DEBUG
    "":
      handlers: [ default ]
      level: WARNING
      propagate: False
    __main__: DEBUG
  registry:
    cooethercat: DEBUG
    pysoem: DEBUG
    lris2csu: DEBUG
    lris2csu.util: INFO
    mktl: DEBUG
    "":
      handlers: [ default ]
      level: WARNING
      propagate: False
    __main__: DEBUG

version: 1
disable_existing_loggers: False
handlers:
  default:
    class : logging.StreamHandler
    formatter: default
    level   : DEBUG
    stream  : ext://sys.stdout
formatters:
  brieffmt:
    format: '%(message)s'
  default:
    format: '%(asctime)s %(name)s:%(levelname)-8s (%(threadName)s) %(message)s'
    datefmt: '%H:%M:%S'
